# 升级需要的倍数
up-need-exp-multiple: 500
# 最高等级
max-level: 200
# 自动备份设置
auto-backup:
  # 是否开启
  enable: true
  # 每次备份间隔(秒)
  time: 900

plot:
  enable: true
  teleport:
    enable: true
    world: world
    x: 0
    y: 0
    z: 0
  words:
    - "一场未知的灾难降临了世界"
    - "导致了大规模的地貌变化和生态崩溃"
    - "原本平静的世界"
    - "变成了一个充满危险和挑战的荒野"
    - "各种奇形怪状的怪物在黑夜中出没"
    - "对人类造成致命的威胁"
    - "人类必须利用有限的资源，建造避难所"
    - "制作武器和工具，寻找食物"
    - "探索未知的领域"
    - "与其他玩家合作或竞争"
    - "生存下去!"