name: WildrnessSurvival
version: '${project.version}'
main: cn.mcwlc.wildrnesssurvival.WildrnessSurvival
api-version: 1.13
authors: [ DongShaoNB ]
description: WildrnessSurvival
website: www.mcwlc.cn
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI

commands:
  wildrnesssurvival:
    description: "WildrnessSurvival Main Command"
    aliases:
      - ws

permissions:
  ws.admin:
    description: "WildrnessSurvival Admin Permission"
    default: op